/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.qualiti.delivery.view;

import br.com.qualiti.delivery.entidades.Cliente;
import br.com.qualiti.delivery.entidades.Entregador;
import br.com.qualiti.delivery.entidades.FormaPagamento;
import br.com.qualiti.delivery.entidades.ItemVenda;
import br.com.qualiti.delivery.entidades.Pedido;
import br.com.qualiti.delivery.entidades.Produto;
import br.com.qualiti.delivery.negocio.Fachada;
import br.com.qualiti.delivery.util.StatusPedido;
import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class CreateEditPedido extends javax.swing.JDialog {

    private Pedido pedidoParaSalvar;

    /**
     * Creates new form CreateEditPedido
     */
    public CreateEditPedido(java.awt.Frame parent, boolean modal, Cliente cliente, Pedido pedidoParaExibir) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        lblNomeCliente.setText(cliente.getNome());
        lblValor.setText("0.0");
        try {
            createTableProdutos(Fachada.getInstancia().buscarTodosProdutos());
            for (Entregador e : Fachada.getInstancia().buscarTodos()) {
                comboEntregador.addItem(e);
            }
            for (FormaPagamento fp : Fachada.getInstancia().buscarTodasFormasPagamento()) {
                comboFormaPagamento.addItem(fp);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        if (pedidoParaExibir != null) {
            btnConcluirPedido.setText("Salvar Pedido");
            pedidoParaSalvar = pedidoParaExibir;
            lblNomeCliente.setText(pedidoParaSalvar.getCliente().getNome());
            createTableItemVenda(pedidoParaSalvar.getItens().toArray(new ItemVenda[pedidoParaSalvar.getItens().size()]));
            comboEntregador.setSelectedItem(pedidoParaSalvar.getEntregador());
            comboFormaPagamento.setSelectedItem(pedidoParaSalvar.getFormaPagamento());
            calculaValorTotal();
        } else {
            pedidoParaSalvar = new Pedido();
            pedidoParaSalvar.setCliente(cliente);
            pedidoParaSalvar.setDataPedido(new Date());
            pedidoParaSalvar.setItens(new ArrayList<ItemVenda>());

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNomeCliente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaItensVenda = new javax.swing.JTable();
        btnAddProduto = new javax.swing.JButton();
        btnRemoverProduto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        btnConcluirPedido = new javax.swing.JButton();
        edtPesquisarProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboEntregador = new javax.swing.JComboBox();
        comboFormaPagamento = new javax.swing.JComboBox();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pedido");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Novo Pedido");

        jLabel2.setText("Cliente: ");

        jLabel3.setText("Produtos:");

        tabelaProdutos.setAutoCreateColumnsFromModel(false);
        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaProdutos);

        jLabel4.setText("Itens de Venda:");

        tabelaItensVenda.setAutoCreateColumnsFromModel(false);
        tabelaItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelaItensVenda);

        btnAddProduto.setText("Adicionar Produto");
        btnAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdutoActionPerformed(evt);
            }
        });

        btnRemoverProduto.setText("Remover Produto");
        btnRemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverProdutoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Valor Total:");

        lblValor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblValor.setForeground(new java.awt.Color(255, 0, 0));

        btnConcluirPedido.setText("Concluir Pedido");
        btnConcluirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirPedidoActionPerformed(evt);
            }
        });

        edtPesquisarProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtPesquisarProdutoKeyReleased(evt);
            }
        });

        jLabel6.setText("Entregador: ");

        jLabel8.setText("Forma de Pagamento:");

        comboEntregador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione" }));
        comboEntregador.setMinimumSize(new java.awt.Dimension(150, 20));
        comboEntregador.setPreferredSize(new java.awt.Dimension(150, 20));
        comboEntregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEntregadorActionPerformed(evt);
            }
        });

        comboFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione" }));
        comboFormaPagamento.setPreferredSize(new java.awt.Dimension(150, 20));
        comboFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFormaPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edtPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddProduto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnConcluirPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoverProduto, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboFormaPagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboEntregador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edtPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddProduto)
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemoverProduto)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboEntregador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(btnConcluirPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdutoActionPerformed

        int index = -1;
        index = tabelaProdutos.getSelectedRow();
        if (index != -1) {
            try {
                Integer codigoProduto = Integer.valueOf(tabelaProdutos.getValueAt(index, 0).toString());
                Produto p = Fachada.getInstancia().procurarProduto(codigoProduto);
                ItemVenda item = new ItemVenda();
                item.setPedido(pedidoParaSalvar);
                item.setProduto(p);
                Integer i = Integer.valueOf(JOptionPane.showInputDialog("Informe a quantidade: "));
                item.setQuantidade(Double.valueOf(String.valueOf(i)));
                item.setValor(p.getPrecoUnitario() * i);
                item.setSequencial(pedidoParaSalvar.getSequencial() + 1);
                item.setPedido(pedidoParaSalvar);
                pedidoParaSalvar.setSequencial(pedidoParaSalvar.getSequencial() + 1);
                pedidoParaSalvar.getItens().add(item);
                createTableItemVenda(pedidoParaSalvar.getItens().toArray(new ItemVenda[pedidoParaSalvar.getItens().size()]));
                calculaValorTotal();
                tabelaProdutos.clearSelection();
            } catch (Exception ex) {
                Logger.getLogger(CreateEditPedido.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAddProdutoActionPerformed

    private void btnRemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverProdutoActionPerformed

        int index = -1;
        index = tabelaItensVenda.getSelectedRow();
        if (index != -1) {
            int sequencial = Integer.valueOf(tabelaItensVenda.getValueAt(index, 0).toString());
            pedidoParaSalvar.getItens().remove(sequencial - 1);
            pedidoParaSalvar.setSequencial(0);
            for (ItemVenda item : pedidoParaSalvar.getItens()) {
                item.setSequencial(pedidoParaSalvar.getSequencial() + 1);
                pedidoParaSalvar.setSequencial(pedidoParaSalvar.getSequencial() + 1);
            }
            createTableItemVenda(pedidoParaSalvar.getItens().toArray(new ItemVenda[pedidoParaSalvar.getItens().size()]));
            calculaValorTotal();
        }
    }//GEN-LAST:event_btnRemoverProdutoActionPerformed

    private void btnConcluirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirPedidoActionPerformed
        try {
            pedidoParaSalvar.setStatus(StatusPedido.SOLICITADO);
            pedidoParaSalvar.validar();
            Fachada.getInstancia().inserir(pedidoParaSalvar);
            JOptionPane.showMessageDialog(this, "Registro inserido com sucesso !", "Criar Pedido", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(CreateEditPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConcluirPedidoActionPerformed


    private void edtPesquisarProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtPesquisarProdutoKeyReleased
        try {
            Produto[] array = null;
            Produto p;
            if (edtPesquisarProduto.getText().isEmpty()) {
                createTableProdutos(Fachada.getInstancia().buscarTodosProdutos());
            } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                if (edtPesquisarProduto.getText().matches("[0-9]+")) {
                    p = Fachada.getInstancia().procurarProduto(Integer.valueOf(edtPesquisarProduto.getText()));
                    if (p != null) {
                        array = new Produto[]{p};
                    }
                } else {
                    p = new Produto();
                    p.setNome(edtPesquisarProduto.getText());
                    Collection<Produto> collection = Fachada.getInstancia().filtrar(p);
                    array = collection.toArray(new Produto[collection.size()]);
                }
                if (array != null) {
                    createTableProdutos(array);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(CreateEditPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_edtPesquisarProdutoKeyReleased

    private void comboEntregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEntregadorActionPerformed
        pedidoParaSalvar.setEntregador((Entregador) comboEntregador.getSelectedItem());
    }//GEN-LAST:event_comboEntregadorActionPerformed

    private void comboFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFormaPagamentoActionPerformed
        pedidoParaSalvar.setFormaPagamento((FormaPagamento) comboFormaPagamento.getSelectedItem());
    }//GEN-LAST:event_comboFormaPagamentoActionPerformed

    private void calculaValorTotal() {
        Double valor = 0.0;
        for (ItemVenda item : pedidoParaSalvar.getItens()) {
            valor += item.getValor();
        }
        lblValor.setText(valor.toString());
    }

    public final void createTableProdutos(Produto[] lista) {
        String[] colunas = {"Código", "Nome", "Preço Unitário"};
        DefaultTableModel model = new DefaultTableModel(colunas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //To change body of generated methods, choose Tools | Templates.
            }
        };

        String[] linha = null;
        if (lista != null) {
            for (Produto p : lista) {
                linha = new String[3];
                linha[0] = p.getCodigo().toString();
                linha[1] = p.getNome();
                linha[2] = p.getPrecoUnitario().toString();
                model.addRow(linha);
            }
        }
        tabelaProdutos.setModel(model);
        tabelaProdutos.createDefaultColumnsFromModel();
    }

    public final void createTableItemVenda(ItemVenda[] items) {
        String[] colunas = {"Sequencial", "Nome", "Quantidade", "Valor"};
        DefaultTableModel model = new DefaultTableModel(colunas, 0) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        String[] linha = null;
        for (ItemVenda i : items) {
            linha = new String[4];
            linha[0] = i.getSequencial().toString();
            linha[1] = i.getProduto().getNome();
            linha[2] = i.getQuantidade().toString();
            linha[3] = i.getValor().toString();
            model.addRow(linha);
        }
        tabelaItensVenda.setModel(model);
        tabelaItensVenda.createDefaultColumnsFromModel();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnConcluirPedido;
    private javax.swing.JButton btnRemoverProduto;
    private javax.swing.JComboBox comboEntregador;
    private javax.swing.JComboBox comboFormaPagamento;
    private javax.swing.JTextField edtPesquisarProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTable tabelaItensVenda;
    private javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables
}
