/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.qualiti.delivery.view;

import br.com.qualiti.delivery.entidades.Entregador;
import br.com.qualiti.delivery.negocio.Fachada;
import br.com.qualiti.delivery.util.Util;
import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author OROMAR
 */
public class CreateEditEntregador extends javax.swing.JDialog {

    private boolean editMode = false;
    private Entregador entregadorToEdit;
    
    
    /**
     * Creates new form CreateEditEntregador
     */
    public CreateEditEntregador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public CreateEditEntregador(Frame parent, String titulo, Entregador entregador) {
        this(parent, true);
        lblTituloEntregador.setText(titulo);
        entregadorToEdit = entregador;
        btnSalvarEntregador.setText("Salvar");
        editMode = true;
        setDadosTela(entregador);
    }

    private void setDadosTela(Entregador entregador) {
        edtCpfEntregador.setEnabled(false);
        edtMatriculaEntregador.setText(entregador.getMatricula());
        edtCpfEntregador.setText(entregador.getCpf());
        edtDataNascimentoEntregador.setText(Util.getDateAsString(entregador.getDataNascimento()));
        edtNomeEntregador.setText(entregador.getNome());
        edtPlacaMotoEntregador.setText(entregador.getPlacaMoto());
        edtModeloMotoEntregador.setText(entregador.getModelo());
        edtTelefoneEntregador.setText(entregador.getTelefone());        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edtMatriculaEntregador2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnSalvarEntregador = new javax.swing.JButton();
        edtMatriculaEntregador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblTituloEntregador = new javax.swing.JLabel();
        edtNomeEntregador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edtPlacaMotoEntregador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edtModeloMotoEntregador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edtTelefoneEntregador = new javax.swing.JTextField();
        edtCpfEntregador = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edtDataNascimentoEntregador = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setText("CPF:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Entregador");
        setIconImage(null);
        setIconImages(null);

        btnSalvarEntregador.setText("Add");
        btnSalvarEntregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEntregadorActionPerformed(evt);
            }
        });

        jLabel1.setText("Matrícula:");

        lblTituloEntregador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTituloEntregador.setText("Novo Entregador");

        jLabel2.setText("Nome:");

        jLabel3.setText("Placa da Moto:");

        jLabel4.setText("Modelo da Moto:");

        jLabel5.setText("Telefone:");

        jLabel6.setText("CPF:");

        jLabel8.setText("Data de Nascimento (DD/MM/YYYY):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloEntregador)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(177, 177, 177)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(193, 193, 193)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(144, 144, 144)
                        .addComponent(jLabel3))
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(edtTelefoneEntregador, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalvarEntregador, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(edtMatriculaEntregador, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(edtCpfEntregador))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(edtNomeEntregador, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(edtDataNascimentoEntregador))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(edtModeloMotoEntregador, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(edtPlacaMotoEntregador, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTituloEntregador)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtMatriculaEntregador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtCpfEntregador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(edtNomeEntregador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(edtDataNascimentoEntregador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtModeloMotoEntregador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtPlacaMotoEntregador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtTelefoneEntregador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarEntregador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarEntregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEntregadorActionPerformed

        if (editMode) {
            try {
                getDadosTela();                
                Fachada.getInstancia().atualizar(entregadorToEdit);
                JOptionPane.showMessageDialog(this, "Registro atualizado com sucesso !", "Info", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }

        } else {

            try {
                getDadosTela();
                Fachada.getInstancia().inserir(entregadorToEdit);
                JOptionPane.showMessageDialog(this, "Registro inserido com sucesso !", "Info", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSalvarEntregadorActionPerformed

    private void getDadosTela() throws Exception {
        entregadorToEdit = new Entregador();
        entregadorToEdit.setCpf(edtCpfEntregador.getText());
        entregadorToEdit.setDateString(edtDataNascimentoEntregador.getText());
        entregadorToEdit.setMatricula(edtMatriculaEntregador.getText());
        entregadorToEdit.setNome(edtNomeEntregador.getText());
        entregadorToEdit.setModelo(edtModeloMotoEntregador.getText());
        entregadorToEdit.setTelefone(edtTelefoneEntregador.getText());
        entregadorToEdit.setPlacaMoto(edtPlacaMotoEntregador.getText());
        entregadorToEdit.validar();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarEntregador;
    private javax.swing.JTextField edtCpfEntregador;
    private javax.swing.JTextField edtDataNascimentoEntregador;
    private javax.swing.JTextField edtMatriculaEntregador;
    private javax.swing.JTextField edtMatriculaEntregador2;
    private javax.swing.JTextField edtModeloMotoEntregador;
    private javax.swing.JTextField edtNomeEntregador;
    private javax.swing.JTextField edtPlacaMotoEntregador;
    private javax.swing.JTextField edtTelefoneEntregador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblTituloEntregador;
    // End of variables declaration//GEN-END:variables
}
