/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.qualiti.delivery.view;

import br.com.qualiti.delivery.entidades.Produto;
import br.com.qualiti.delivery.negocio.Fachada;
import javax.swing.JOptionPane;

/**
 *
 * @author OROMAR
 */
public class CreateEditProduto extends javax.swing.JDialog {

    private boolean editMode;
    private Produto produtoParaAtualizar;

    /**
     * Creates new form TelaCriarEditarProduto
     */
    public CreateEditProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public CreateEditProduto(java.awt.Frame parent, String titulo, Produto produto) {
        this(parent, true);
        produtoParaAtualizar = produto;
        editMode = true;
        setTitle(titulo);
        btnAddProduto.setText("Salvar");
        edtDataValidadeProduto.setText(produtoParaAtualizar.getDateString());
        edtNomeProduto.setText(produtoParaAtualizar.getNome());
        edtPrecoProduto.setText(String.valueOf(produto.getPrecoUnitario()));
        lblNovoProduto.setText("Editar Produto");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNovoProduto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edtNomeProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edtPrecoProduto = new javax.swing.JTextField();
        edtDataValidadeProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAddProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Produto");
        setResizable(false);

        lblNovoProduto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNovoProduto.setText("Novo Produto");

        jLabel2.setText("Nome:");

        jLabel3.setText("Preço Unitário:");

        jLabel4.setText("Data de Validade:");

        btnAddProduto.setText("Add");
        btnAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtPrecoProduto)
                    .addComponent(edtNomeProduto)
                    .addComponent(edtDataValidadeProduto)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNovoProduto)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 161, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddProduto)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblNovoProduto)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtDataValidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdutoActionPerformed

        try {
            if (editMode) {
                produtoParaAtualizar.setNome(edtNomeProduto.getText());
                produtoParaAtualizar.setDateString(edtDataValidadeProduto.getText());
                produtoParaAtualizar.setPrecoUnitario(Double.parseDouble(edtPrecoProduto.getText()));
                produtoParaAtualizar.validar();
                Fachada.getInstancia().atualizar(produtoParaAtualizar);
                JOptionPane.showMessageDialog(this, "Registro atualizado com sucesso !", "Info", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } else {
                Produto novoProduto = null;
                novoProduto = new Produto();
                novoProduto.setNome(edtNomeProduto.getText());
                novoProduto.setPrecoUnitario(Double.parseDouble(edtPrecoProduto.getText()));
                novoProduto.setDateString(edtDataValidadeProduto.getText());
                novoProduto.validar();
                Fachada.getInstancia().inserir(novoProduto);
                JOptionPane.showMessageDialog(this, "Registro inserido com sucesso !", "Info", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddProdutoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JTextField edtDataValidadeProduto;
    private javax.swing.JTextField edtNomeProduto;
    private javax.swing.JTextField edtPrecoProduto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblNovoProduto;
    // End of variables declaration//GEN-END:variables
}
