/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.qualiti.delivery.view;

import br.com.qualiti.delivery.entidades.FormaPagamento;
import br.com.qualiti.delivery.negocio.Fachada;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author OROMAR
 */
public class CreateEditFormaPagamento extends javax.swing.JDialog {

    private boolean editMode = false;
    private FormaPagamento formaPagamentoToEdit;

    /**
     * Creates new form TelaCriarEditarFormaPagamento
     */
    public CreateEditFormaPagamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public CreateEditFormaPagamento(java.awt.Frame parent, String titulo, FormaPagamento formaPagamento, boolean enabled) {
        this(parent, true);
        setTitle("Alterar Formar de Pagammento");
        labelTituloFormaPagamento.setText(titulo);
        edtNomeFormaPagamento.setText(formaPagamento.getNome());
        btnSalvarFormaPagamento.setText("Salvar");
        editMode = true;
        formaPagamentoToEdit = formaPagamento;
        setLocationRelativeTo(null);
        edtNomeFormaPagamento.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        labelTituloFormaPagamento = new javax.swing.JLabel();
        edtNomeFormaPagamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSalvarFormaPagamento = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Forma de Pagamento");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        labelTituloFormaPagamento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTituloFormaPagamento.setText("Nova Forma de Pagamento");

        jLabel1.setText("Nome:");

        btnSalvarFormaPagamento.setText("Add");
        btnSalvarFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarFormaPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(labelTituloFormaPagamento)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(edtNomeFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvarFormaPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloFormaPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtNomeFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarFormaPagamento))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarFormaPagamentoActionPerformed

        if (editMode) {
            try {
                formaPagamentoToEdit.setNome(edtNomeFormaPagamento.getText());
                Fachada.getInstancia().atualizar(formaPagamentoToEdit);
                JOptionPane.showMessageDialog(this, "Registro atualizado com sucesso !", "Info", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
            
        } else {

            try {
                String nomeFormaPagamento = edtNomeFormaPagamento.getText();
                FormaPagamento formaPagamento = new FormaPagamento();
                formaPagamento.setNome(nomeFormaPagamento);
                formaPagamento.validar();
                Fachada.getInstancia().inserir(formaPagamento);
                JOptionPane.showMessageDialog(this, "Registro inserido com sucesso !", "Info", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSalvarFormaPagamentoActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
    }//GEN-LAST:event_formKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarFormaPagamento;
    private javax.swing.JTextField edtNomeFormaPagamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelTituloFormaPagamento;
    // End of variables declaration//GEN-END:variables
}
