/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.qualiti.delivery.view;

import br.com.qualiti.delivery.entidades.Cliente;
import br.com.qualiti.delivery.entidades.Pedido;
import br.com.qualiti.delivery.negocio.Fachada;
import br.com.qualiti.delivery.util.StatusPedido;
import br.com.qualiti.delivery.util.Util;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author OROMAR
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        URL url = this.getClass().getResource("/resources/logo.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnItemSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnItemCliente = new javax.swing.JMenuItem();
        mnIemEntregador = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuItemFormaPagamento = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemNovoPedido = new javax.swing.JMenuItem();
        mnItemConsultarPedido = new javax.swing.JMenuItem();
        mnItemFinalizarPedido = new javax.swing.JMenuItem();
        mnItemCancelarPedido = new javax.swing.JMenuItem();
        menuAvancado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Qualiti Delivery System");
        setIconImages(null);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("F2 - CLIENTES  F3 - ENTREGADOR  F4 - PRODUTO  F5 - FORMA DE PAGAMENTO ");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        jMenu1.setText("Sistema");

        mnItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnItemSair.setText("Sair");
        mnItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(mnItemSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastro");

        mnItemCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mnItemCliente.setText("Cliente");
        mnItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemClienteActionPerformed(evt);
            }
        });
        jMenu2.add(mnItemCliente);

        mnIemEntregador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        mnIemEntregador.setText("Entregador");
        mnIemEntregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIemEntregadorActionPerformed(evt);
            }
        });
        jMenu2.add(mnIemEntregador);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem4.setText("Produto");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        menuItemFormaPagamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        menuItemFormaPagamento.setText("Forma de Pagamento");
        menuItemFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormaPagamentoActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemFormaPagamento);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Pedido");

        menuItemNovoPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        menuItemNovoPedido.setText("Novo");
        menuItemNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovoPedidoActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemNovoPedido);

        mnItemConsultarPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        mnItemConsultarPedido.setText("Consultar");
        mnItemConsultarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemConsultarPedidoActionPerformed(evt);
            }
        });
        jMenu3.add(mnItemConsultarPedido);

        mnItemFinalizarPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        mnItemFinalizarPedido.setText("Finalizar");
        mnItemFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemFinalizarPedidoActionPerformed(evt);
            }
        });
        jMenu3.add(mnItemFinalizarPedido);

        mnItemCancelarPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        mnItemCancelarPedido.setText("Cancelar");
        mnItemCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemCancelarPedidoActionPerformed(evt);
            }
        });
        jMenu3.add(mnItemCancelarPedido);

        menuAvancado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        menuAvancado.setText("Avançado");
        menuAvancado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAvancadoActionPerformed(evt);
            }
        });
        jMenu3.add(menuAvancado);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ListProduto tela = new ListProduto(this, true);
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mnItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemSairActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente sair do Sistema ?", "Sair", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_mnItemSairActionPerformed

    private void mnItemCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemCancelarPedidoActionPerformed
        try {
            Integer codigoPedido = Util.getCodigoComoInteger("Cancelar Pedido", "Digite o código do pedido:");
            Pedido pedido = Fachada.getInstancia().procurarPedido(codigoPedido);
            if (pedido != null) {
                if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this, "Confirma cancelar pedido ?", "Cancelar Pedido", JOptionPane.YES_NO_OPTION)) {
                    pedido.setStatus(StatusPedido.CANCELADO);
                    Fachada.getInstancia().atualizar(pedido);
                    JOptionPane.showMessageDialog(this, "Pedido cancelado com sucesso !", "Cancelar Pedido", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnItemCancelarPedidoActionPerformed

    private void mnItemFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemFinalizarPedidoActionPerformed
        try {
            Integer codigoPedido = Util.getCodigoComoInteger("Finalizar Pedido", "Digite o código do pedido:");
            Pedido pedido = Fachada.getInstancia().procurarPedido(codigoPedido);
            if (pedido != null) {
                if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this, "Confirma finalizar pedido ?", "Finalizar Pedido", JOptionPane.YES_NO_OPTION)) {
                    pedido.setStatus(StatusPedido.ENTREGUE);
                    Fachada.getInstancia().atualizar(pedido);
                    JOptionPane.showMessageDialog(this, "Pedido finalizado com sucesso !", "Finalizar Pedido", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnItemFinalizarPedidoActionPerformed

    private void mnItemConsultarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemConsultarPedidoActionPerformed
        try {
            Integer codigoPedido = Util.getCodigoComoInteger("Consultar Pedido", "Digite o código do pedido:");
            if (codigoPedido != null) {
                Pedido pedido = Fachada.getInstancia().procurarPedido(codigoPedido);
                if (pedido != null) {
                    CreateEditPedido tela = new CreateEditPedido(this, true, pedido.getCliente(), pedido);
                    tela.setVisible(true);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_mnItemConsultarPedidoActionPerformed

    private void menuItemFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormaPagamentoActionPerformed
        ListFormaPagamento telaListarFormaPagamento = new ListFormaPagamento(this, true);
        telaListarFormaPagamento.setLocationRelativeTo(this);
        telaListarFormaPagamento.setVisible(true);
    }//GEN-LAST:event_menuItemFormaPagamentoActionPerformed

    private void menuItemNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNovoPedidoActionPerformed
        try {
            String cpf = Util.getCodigoComoString("Novo Pedido", "Digite o CPF do cliente:");
            if (cpf != null && !cpf.isEmpty()) {
                Cliente cliente = Fachada.getInstancia().procurarCliente(cpf);
                if (cliente != null) {
                    CreateEditPedido tela = new CreateEditPedido(this, true, cliente, null);
                    tela.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Cliente não encontrado !", "Cliente não encontrado", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemNovoPedidoActionPerformed

    private void mnIemEntregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIemEntregadorActionPerformed

        ListEntregador tela = new ListEntregador(this, true);
        tela.setLocationRelativeTo(this);
        tela.setVisible(true);

    }//GEN-LAST:event_mnIemEntregadorActionPerformed

    private void menuAvancadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAvancadoActionPerformed
       
        ListPedido list = new ListPedido(this, true);
        list.setVisible(true);
        
        
    }//GEN-LAST:event_menuAvancadoActionPerformed

    private void mnItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemClienteActionPerformed
        ListCliente listCliente = new ListCliente(this, true);
        listCliente.setLocationRelativeTo(this);
        listCliente.setVisible(true);
    }//GEN-LAST:event_mnItemClienteActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem menuAvancado;
    private javax.swing.JMenuItem menuItemFormaPagamento;
    private javax.swing.JMenuItem menuItemNovoPedido;
    private javax.swing.JMenuItem mnIemEntregador;
    private javax.swing.JMenuItem mnItemCancelarPedido;
    private javax.swing.JMenuItem mnItemCliente;
    private javax.swing.JMenuItem mnItemConsultarPedido;
    private javax.swing.JMenuItem mnItemFinalizarPedido;
    private javax.swing.JMenuItem mnItemSair;
    // End of variables declaration//GEN-END:variables
}
